### ISSUE TITLE
`:global()` support

### ISSUE THREAD

**Issue by ehzro3** [ryboe/CSS3#178]
<img width="252" alt="Screen Shot 2021-12-22 at 11 16 15" src="https://user-images.githubusercontent.com/40330010/147023799-c1a00733-957e-44ed-9c35-4870cdd42b41.png">

Hi :)

I'm using CSS3 with Svelte, and it seems CSS3 doesn't get Svelte `global()`.
Could they know each other better?

**Comment by argyleink** [comment]
this package seeks to follow the specs and `:global` is a concept from [CSS Modules](https://github.com/css-modules/css-modules). IMO it shouldnt be part of this package, but I do empathize with wanting to see that properly highlighted. 

i've "shown the package contents" for the plugin and edited `CSS3.sublime-syntax` so global highlights, check it out:

![Screen Shot 2022-01-04 at 11 21 16 AM](https://user-images.githubusercontent.com/1134620/148112452-559f12ef-8dee-45f1-ba1e-806945c0ec7c.png)

before:
<img width="250" alt="before" src="https://user-images.githubusercontent.com/1134620/148112481-7aa2cbba-7ad9-4ca9-918e-efe9996348c5.png">


after:
<img width="253" alt="after" src="https://user-images.githubusercontent.com/1134620/148112479-cffd51d6-7a40-4ebd-82e1-8cdfc60471c9.png">

took me just a minute or 2, and should allow you to pacify that nagging highlighting. thoughts on a self patch instead of having the fix be upstream?

**Comment by mustafa0x** [comment]
Would like to see this in upstream too. Not sure how to show package contents.

There's quite a lot of usage of `:global()`. Github search tells me 18.1k files.

https://github.com/search?q=language%3Asvelte+%3Aglobal%28&type=code

**Comment by vrugtehagel** [comment]
Just to clarify why this change is unlikely to happen upstream; CSS3 provides very specific syntax highlighting to help users write valid, spec-compliant CSS, as opposed to generically highlight anything that looks like it could be CSS. The `:global()` selector falls into the second category; it's not valid CSS, but it's an addition that some frameworks have added.

In particular, if CSS3 would add support for `:global()`, then users who use CSS3 to help them point out mistakes in their (pure) CSS may be incorrectly inclined to believe `:global()` is a real thing and wonder why it's not doing anything.

Adding it would also open the door to adding a wide array of other framework-specific helpers (such as Vue's `:deep()`) and at that point the package highlights both valid _and_ invalid (i.e. non-spec-compliant) CSS. Users would no longer have trust that their highlighted code is valid CSS. In a nutshell, it would grow towards just being a generic highlighter with no validation whatsoever, which I feel completely misses the philosophy of this highlighting package.

I suggest the issue to be closed, to avoid users hoping this'll happen one day.
