### ISSUE TITLE
autocomplete doesn't work anyway

### ISSUE THREAD

**Issue by APEXRARE2009** [ryboe/CSS3#217]
autocomplete doesn't work anyway, it's missing altogether, as if
here is the video - https://disk.yandex.ru/i/K4U6qNx4I02qTw

**Comment by vrugtehagel** [comment]
Hey @APEXRARE2009! Appreciate you filing an issue, but let's try not to create unnecessary administrative work for the maintainers of this repository. You've opened an issue recently already, which was closed as a duplicate of https://github.com/ryboe/CSS3/issues/198. This, too, is a duplicate; please contribute your additional comments to that issue instead of opening a new one. Thanks!

**Comment by vrugtehagel** [comment]
@argyleink this issue can be closed, it was resolved with https://github.com/ryboe/CSS3/issues/198
